# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Write a numeric matrix to a PGM file
#'
#' @param mat numeric matrix
#' @param filename output filename e.g "example.pgm"
#' @param convert_to_row_major Convert to row-major order before output. R stores matrix
#'        and array data in column-major order. In order to output row-major order (as
#'        expected by PGM/PPM image format) data ordering must be converted. If this argument
#'        is set to FALSE, then image output will be faster (due to fewer data-ordering operations, and
#'        better cache coherency) but the image will be transposed. Default: TRUE
#' @param intensity_factor Multiplication factor applied to all values in image
#'        (note: no checking is performed to ensure values remain in range [0, 1]).
#'        If intensity_factor <= 0, then automatically determine (and apply) a multiplication factor
#'        to set the maximum value to 1.0. Default: intensity_factor = 1.0
#'
#'
write_pgm <- function(mat, filename, convert_to_row_major = TRUE, intensity_factor = 1) {
    invisible(.Call(`_foist_write_pgm`, mat, filename, convert_to_row_major, intensity_factor))
}

#' Write a numeric matrix to a PPM file using the specified palette
#'
#' @param mat numeric matrix with values in range [0, 1]
#' @param pal integer matrix of size 256x3 with values in the range [0, 255]. Each
#'        row represents the r, g, b colour fo ra given grey index value.
#' @param filename output filename e.g. "example.ppm"
#' @param convert_to_row_major Convert to row-major order before output. R stores matrix
#'        and array data in column-major order. In order to output row-major order (as
#'        expected by PGM/PPM image format) data ordering must be converted. If this argument
#'        is set to FALSE, then image output will be faster (due to fewer data-ordering operations, and
#'        better cache coherency) but the image will be transposed. Default: TRUE
#' @param intensity_factor Multiplication factor applied to all values in image
#'        (note: no checking is performed to ensure values remain in range [0, 1]).
#'        If intensity_factor <= 0, then automatically determine (and apply) a multiplication factor
#'        to set the maximum value to 1.0. Default: intensity_factor = 1.0
#'
#'
write_pal_ppm <- function(mat, pal, filename, convert_to_row_major = TRUE, intensity_factor = 1) {
    invisible(.Call(`_foist_write_pal_ppm`, mat, pal, filename, convert_to_row_major, intensity_factor))
}

#' Write a numeric array to a PPM file
#'
#' @param arr numeric array with 3 planes. Because Rcpp doesn't explicitly
#'        handle arrays, they are treated as \code{NumericVector} and
#'        dimensions must be handled manually.
#' @param dims integer vector of length 3. image dimensions: c(nrow, ncol, depth). Depth must be 3.
#' @param filename output filename e.g. "example.ppm"
#' @param convert_to_row_major Convert to row-major order before output. R stores matrix
#'        and array data in column-major order. In order to output row-major order (as
#'        expected by PGM/PPM image format) data ordering must be converted. If this argument
#'        is set to FALSE, then image output will be faster (due to fewer data-ordering operations, and
#'        better cache coherency) but the image will be transposed. Default: TRUE
#' @param intensity_factor Multiplication factor applied to all values in image
#'        (note: no checking is performed to ensure values remain in range [0, 1]).
#'        If intensity_factor <= 0, then automatically determine (and apply) a multiplication factor
#'        to set the maximum value to 1.0. Default: intensity_factor = 1.0
#'
#'
write_ppm_core <- function(arr, dims, filename, convert_to_row_major = TRUE, intensity_factor = 1) {
    invisible(.Call(`_foist_write_ppm_core`, arr, dims, filename, convert_to_row_major, intensity_factor))
}

